In [2]:
#import libraries
import pandas as pd
import numpy as np

In [3]:
#load csv file with headers 
location = "Datasets/DC_Properties.csv"
df = pd.read_csv(location)

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
df.head()

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [5]:
df.tail(3)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
158954,158954,2,0,Forced Air,Y,NaN,4,2,1920.0,2007.0,...,-77.01942,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158955,158955,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.01823,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW
158956,158956,1,0,Warm Cool,Y,NaN,2,0,1965.0,NaN,...,-77.01823,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,504,-77.018232,38.872961,SW

In [12]:
df['PRICE'].max()

137427545.0

In [14]:
df['PRICE'].min()

1.0

In [15]:
df['PRICE'].median()

399999.0

In [16]:
df['PRICE'].mean()

931351.5949336156

In [10]:
df['GRADE'].value_counts()

Average          37357
Above Average    32101
Good Quality     20800
Very Good         8976
Excellent         3390
Superior          2634
Exceptional-A      818
Exceptional-B      278
Fair Quality       150
Exceptional-C       92
Exceptional-D       75
No Data             19
Low Quality          6
Name: GRADE, dtype: int64

In [13]:
df['AYB'].value_counts()

1900.0    8967
1925.0    5129
1910.0    4563
1940.0    4316
1923.0    3724
1927.0    3707
1941.0    3420
1926.0    3117
1942.0    3058
1939.0    2849
1950.0    2696
1937.0    2690
1936.0    2553
2007.0    2291
1908.0    2274
1912.0    2272
1938.0    2246
1928.0    2190
1909.0    2154
2005.0    2146
1951.0    2086
1947.0    2058
1920.0    2019
2006.0    2019
1890.0    1976
1930.0    1884
1929.0    1838
1960.0    1816
1948.0    1808
1911.0    1807
          ...
1819.0       2
1835.0       2
1861.0       2
1847.0       2
1849.0       2
1824.0       2
1808.0       1
1793.0       1
1765.0       1
1866.0       1
1782.0       1
1784.0       1
1785.0       1
1787.0       1
1788.0       1
1854.0       1
1791.0       1
1851.0       1
1834.0       1
1795.0       1
1822.0       1
1797.0       1
1799.0       1
1833.0       1
1846.0       1
1844.0       1
1842.0       1
1841.0       1
1806.0       1
2019.0       1
Name: AYB, Length: 220, dtype: int64

In [20]:
df['STRUCT'].groupby(df['AYB']).mean

In [21]:
df['GBA'].unique()

array([ 2522.,  2567.,  2484., ...,  5712.,  4995.,    nan])

In [25]:
#find missing values 
filename = "datasets/DC_Properties.csv"
df_missing = pd.read_csv(filename)

df_missing.head()

C:\ProgramData\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2698: DtypeWarning: Columns (18,19,20,21,22,23,24,33,34,35,37,43,45) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
0,0,4,0,Warm Cool,Y,2.0,8,4,1910.0,1988.0,...,-77.040832,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
1,1,3,1,Warm Cool,Y,2.0,11,5,1898.0,2007.0,...,-77.040764,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
2,2,3,1,Hot Water Rad,Y,2.0,9,5,1910.0,2009.0,...,-77.040678,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
3,3,3,1,Hot Water Rad,Y,2.0,8,5,1900.0,2003.0,...,-77.040629,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW

In [24]:
df_missing.isnull().sum()

NameError: name 'df_missing' is not defined

In [26]:
missing = df_missing['SALEDATE'].isnull()
df_missing.loc[missing]

,Unnamed: 0,BATHRM,HF_BATHRM,HEAT,AC,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,...,LONGITUDE,ASSESSMENT_NBHD,ASSESSMENT_SUBNBHD,CENSUS_TRACT,CENSUS_BLOCK,WARD,SQUARE,X,Y,QUADRANT
4,4,2,1,Warm Cool,Y,1.0,11,3,1913.0,2012.0,...,-77.039361,Old City 2,040 D Old City 2,4201.0,004201 2006,Ward 2,152,-77.040429,38.914881,NW
10,10,3,0,Forced Air,N,3.0,12,5,1890.0,1950.0,...,-77.040760,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
12,12,2,0,Hot Water Rad,N,2.0,9,5,1894.0,1979.0,...,-77.039569,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
13,13,2,0,Warm Cool,Y,2.0,11,5,1885.0,1979.0,...,-77.039644,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
15,15,2,1,Warm Cool,Y,2.0,9,4,1908.0,1990.0,...,-77.039784,Old City 2,040 D Old City 2,4201.0,004201 2005,Ward 2,152,-77.040429,38.914881,NW
26,26,1,0,Hot Water Rad,N,1.0,10,5,1900.0,2004.0,...,-77.034258,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
30,30,2,1,Forced Air,Y,2.0,8,3,1900.0,2004.0,...,-77.033993,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
33,33,2,1,Forced Air,Y,2.0,10,3,1900.0,2004.0,...,-77.033640,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
36,36,3,1,Warm Cool,Y,2.0,10,4,1800.0,1975.0,...,-77.033431,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
38,38,3,1,Forced Air,Y,2.0,9,4,1800.0,2004.0,...,-77.033294,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
39,39,3,1,Warm Cool,Y,2.0,9,4,1976.0,NaN,...,-77.033225,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
51,51,3,0,Forced Air,Y,3.0,9,3,1890.0,2004.0,...,-77.033361,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
53,53,2,1,Warm Cool,Y,2.0,7,4,1890.0,1978.0,...,-77.033644,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
57,57,1,0,Hot Water Rad,Y,1.0,6,3,1885.0,NaN,...,-77.035813,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
60,60,2,0,Hot Water Rad,N,2.0,9,2,1870.0,1980.0,...,-77.034766,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
63,63,3,1,Forced Air,Y,2.0,13,5,1900.0,1999.0,...,-77.036164,Old City 2,040 E Old City 2,4300.0,004300 2006,Ward 2,191,-77.035454,38.914956,NW
80,80,2,1,Warm Cool,Y,2.0,11,3,1979.0,NaN,...,-77.037858,Old City 2,040 D Old City 2,4201.0,004201 1002,Ward 2,176,-77.037830,38.916190,NW
83,83,2,1,Warm Cool,Y,2.0,11,3,1979.0,NaN,...,-77.037915,Old City 2,040 D Old City 2,4201.0,004201 1002,Ward 2,176,-77.037830,38.916190,NW
87,87,1,1,Hot Water Rad,Y,2.0,6,3,1865.0,NaN,...,-77.037394,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
88,88,2,2,Hot Water Rad,N,1.0,8,4,1865.0,NaN,...,-77.037471,Old City 2,040 D Old City 2,4201.0,004201 1006,Ward 2,177,-77.037221,38.915033,NW
104,104,4,1,Warm Cool,Y,1.0,11,6,1900.0,NaN,...,-77.046366,Old City 2,040 D Old City 2,5500.0,005500 1001,Ward 2,92,-77.046148,38.913145,NW
109,109,2,1,Warm Cool,Y,1.0,13,5,1890.0,2004.0,...,-77.045920,Old City 2,040 D Old City 2,5500.0,005500 1005,Ward 2,93,-77.045889,38.912003,NW
111,111,2,2,Warm Cool,Y,2.0,10,5,1885.0,NaN,...,-77.046061,Old City 2,040 D Old City 2,5500.0,005500 1005,Ward 2,93,-77.045889,38.912003,NW
125,125,3,1,Warm Cool,Y,2.0,10,5,1922.0,2007.0,...,-77.045969,Old City 2,040 D Old City 2,5500.0,005500 1004,Ward 2,93,-77.045889,38.912003,NW
147,147,1,1,Warm Cool,Y,1.0,5,2,1939.0,NaN,...,-77.041986,Old City 2,040 D Old City 2,4202.0,004202 1008,Ward 2,134,-77.042719,38.912019,NW
155,155,1,1,Warm Cool,Y,1.0,6,3,1907.0,2012.0,...,-77.038703,Old City 2,040 D Old City 2,4201.0,004201 2000,Ward 1,149,-77.038764,38.918277,NW
159,159,2,0,Warm Cool,Y,1.0,6,3,1900.0,NaN,...,-77.038697,Old City 2,040 D Old City 2,4201.0,004201 2000,Ward 1,149,-77.038764,38.918277,NW
164,164,1,1,Warm Cool,Y,1.0,6,3,1880.0,NaN,...,-77.039058,Old City 2,040 D Old City 2,4201.0,004201 2002,Ward 1,150,-77.039567,38.917462,NW
174,174,2,0,Hot Water Rad,N,1.0,8,4,1900.0,NaN,...,-77.034288,Old City 2,040 E Old City 2,5201.0,005201 4003,Ward 2,208,-77.033366,38.911716,NW
176,176,1,0,Hot Water Rad,N,1.0,9,2,1895.0,2008.0,...,-77.032450,Old City 2,040 E Old City 2,5201.0,005201 4002,Ward 2,208,-77.033366,38.911716,NW
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
158673,158673,2,1,Warm Cool,Y,NaN,6,2,1961.0,NaN,...,-77.014271,Southwest Waterfront,NaN,10500.0,NaN,Ward 6,540,-77.014273,38.880828,SW
158674,158674,2,2,Warm Cool,Y,NaN,10,4,1961.0,NaN,...,-77.014271,Southwest Waterfront,NaN,10500.0,NaN,Ward 6,540,-77.014273,38.880828,SW
158681,158681,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158696,158696,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158698,158698,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158718,158718,2,1,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158721,158721,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158723,158723,3,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158728,158728,2,1,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.016301,Southwest Waterfront,NaN,11000.0,NaN,Ward 6,546,-77.016303,38.874797,SW
158832,158832,2,0,Warm Cool,Y,NaN,5,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158837,158837,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158840,158840,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158842,158842,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158847,158847,2,0,Warm Cool,Y,NaN,6,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158848,158848,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158849,158849,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158859,158859,2,0,Warm Cool,Y,NaN,6,3,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158860,158860,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158863,158863,1,0,Warm Cool,Y,NaN,3,1,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158866,158866,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158872,158872,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158883,158883,1,0,Warm Cool,Y,NaN,4,2,1967.0,NaN,...,-77.020322,Southwest Waterfront,NaN,10200.0,NaN,Ward 6,468,-77.020324,38.880130,SW
158913,158913,2,1,Forced Air,Y,NaN,4,2,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158917,158917,2,1,Forced Air,Y,NaN,4,2,2014.0,NaN,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158922,158922,1,0,Ht Pump,Y,NaN,5,2,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158923,158923,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158925,158925,2,0,Ht Pump,Y,NaN,6,3,1993.0,1993.0,...,-77.019274,Old City 2,040 G Old City 2,4801.0,NaN,Ward 6,475,-77.019277,38.914287,NW
158937,158937,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158941,158941,1,0,Forced Air,Y,NaN,4,2,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW
158942,158942,2,0,Forced Air,Y,NaN,7,4,1992.0,1992.0,...,-77.019420,Old City 2,040 B Old City 2,4801.0,NaN,Ward 6,477,-77.019422,38.911848,NW

In [27]:
df_missing.isnull().sum()

Unnamed: 0                 0
BATHRM                     0
HF_BATHRM                  0
HEAT                       0
AC                         0
NUM_UNITS              52261
ROOMS                      0
BEDRM                      0
AYB                      271
YR_RMDL                78029
EYB                        0
STORIES                52305
SALEDATE               26770
PRICE                  60741
QUALIFIED                  0
SALE_NUM                   0
GBA                    52261
BLDG_NUM                   0
STYLE                  52261
STRUCT                 52261
GRADE                  52261
CNDTN                  52261
EXTWALL                52261
ROOF                   52261
INTWALL                52261
KITCHENS               52262
FIREPLACES                 0
USECODE                    0
LANDAREA                   0
GIS_LAST_MOD_DTTM          0
SOURCE                     0
CMPLX_NUM             106696
LIVING_GBA            106696
FULLADDRESS            52917
CITY                   52906
STATE                  52906
ZIPCODE                    1
NATIONALGRID           52906
LATITUDE                   1
LONGITUDE                  1
ASSESSMENT_NBHD            1
ASSESSMENT_SUBNBHD     32551
CENSUS_TRACT               1
CENSUS_BLOCK           52906
WARD                       1
SQUARE                     0
X                        237
Y                        237
QUADRANT                 237
dtype: int64

In [28]:
df.columns

Index(['Unnamed: 0', 'BATHRM', 'HF_BATHRM', 'HEAT', 'AC', 'NUM_UNITS', 'ROOMS',
       'BEDRM', 'AYB', 'YR_RMDL', 'EYB', 'STORIES', 'SALEDATE', 'PRICE',
       'QUALIFIED', 'SALE_NUM', 'GBA', 'BLDG_NUM', 'STYLE', 'STRUCT', 'GRADE',
       'CNDTN', 'EXTWALL', 'ROOF', 'INTWALL', 'KITCHENS', 'FIREPLACES',
       'USECODE', 'LANDAREA', 'GIS_LAST_MOD_DTTM', 'SOURCE', 'CMPLX_NUM',
       'LIVING_GBA', 'FULLADDRESS', 'CITY', 'STATE', 'ZIPCODE', 'NATIONALGRID',
       'LATITUDE', 'LONGITUDE', 'ASSESSMENT_NBHD', 'ASSESSMENT_SUBNBHD',
       'CENSUS_TRACT', 'CENSUS_BLOCK', 'WARD', 'SQUARE', 'X', 'Y', 'QUADRANT'],
      dtype='object')

In [29]:
df.dtypes

Unnamed: 0              int64
BATHRM                  int64
HF_BATHRM               int64
HEAT                   object
AC                     object
NUM_UNITS             float64
ROOMS                   int64
BEDRM                   int64
AYB                   float64
YR_RMDL               float64
EYB                     int64
STORIES               float64
SALEDATE               object
PRICE                 float64
QUALIFIED              object
SALE_NUM                int64
GBA                   float64
BLDG_NUM                int64
STYLE                  object
STRUCT                 object
GRADE                  object
CNDTN                  object
EXTWALL                object
ROOF                   object
INTWALL                object
KITCHENS              float64
FIREPLACES              int64
USECODE                 int64
LANDAREA                int64
GIS_LAST_MOD_DTTM      object
SOURCE                 object
CMPLX_NUM             float64
LIVING_GBA            float64
FULLADDRESS            object
CITY                   object
STATE                  object
ZIPCODE               float64
NATIONALGRID           object
LATITUDE              float64
LONGITUDE             float64
ASSESSMENT_NBHD        object
ASSESSMENT_SUBNBHD     object
CENSUS_TRACT          float64
CENSUS_BLOCK           object
WARD                   object
SQUARE                 object
X                     float64
Y                     float64
QUADRANT               object
dtype: object

In [30]:
df.count()

Unnamed: 0            158957
BATHRM                158957
HF_BATHRM             158957
HEAT                  158957
AC                    158957
NUM_UNITS             106696
ROOMS                 158957
BEDRM                 158957
AYB                   158686
YR_RMDL                80928
EYB                   158957
STORIES               106652
SALEDATE              132187
PRICE                  98216
QUALIFIED             158957
SALE_NUM              158957
GBA                   106696
BLDG_NUM              158957
STYLE                 106696
STRUCT                106696
GRADE                 106696
CNDTN                 106696
EXTWALL               106696
ROOF                  106696
INTWALL               106696
KITCHENS              106695
FIREPLACES            158957
USECODE               158957
LANDAREA              158957
GIS_LAST_MOD_DTTM     158957
SOURCE                158957
CMPLX_NUM              52261
LIVING_GBA             52261
FULLADDRESS           106040
CITY                  106051
STATE                 106051
ZIPCODE               158956
NATIONALGRID          106051
LATITUDE              158956
LONGITUDE             158956
ASSESSMENT_NBHD       158956
ASSESSMENT_SUBNBHD    126406
CENSUS_TRACT          158956
CENSUS_BLOCK          106051
WARD                  158956
SQUARE                158957
X                     158720
Y                     158720
QUADRANT              158720
dtype: int64

In [31]:
df['PRICE'].std

<bound method Series.std of 0         1095000.0
1               NaN
2         2100000.0
3         1602000.0
4               NaN
5         1950000.0
6               NaN
7         1050000.0
8         1430000.0
9               NaN
10              NaN
11              NaN
12              NaN
13              NaN
14        1325000.0
15              NaN
16        1240000.0
17              NaN
18              NaN
19         592250.0
20          33232.0
21              NaN
22         907400.0
23        1065000.0
24        1100000.0
25          20000.0
26              NaN
27         703700.0
28              NaN
29        1210000.0
            ...
158927          NaN
158928     632400.0
158929     574000.0
158930     365000.0
158931     405000.0
158932     505000.0
158933     520000.0
158934     499900.0
158935     451000.0
158936     564900.0
158937          NaN
158938     660000.0
158939     380000.0
158940          NaN
158941          NaN
158942          NaN
158943     539000.0
158944     908500.0
158945     450000.0
158946     485355.0
158947     320000.0
158948     460000.0
158949     550000.0
158950     635000.0
158951     389000.0
158952     399900.0
158953     416000.0
158954     600000.0
158955     215100.0
158956          NaN
Name: PRICE, Length: 158957, dtype: float64>

In [32]:
df.describe()

,Unnamed: 0,BATHRM,HF_BATHRM,NUM_UNITS,ROOMS,BEDRM,AYB,YR_RMDL,EYB,STORIES,...,USECODE,LANDAREA,CMPLX_NUM,LIVING_GBA,ZIPCODE,LATITUDE,LONGITUDE,CENSUS_TRACT,X,Y
count,158957.000000,158957.000000,158957.000000,106696.000000,158957.000000,158957.000000,158686.000000,80928.000000,158957.000000,106652.000000,...,158957.000000,158957.000000,52261.000000,52261.000000,158956.000000,158956.000000,158956.000000,158956.000000,158720.000000,158720.000000
mean,79478.000000,1.810678,0.458237,1.198039,6.187736,2.732506,1941.987579,1998.243537,1963.718024,2.091793,...,14.252999,2473.282158,2371.544249,888.834542,20012.694563,38.914854,-77.016676,5348.216324,-77.016712,38.914846
std,45887.077707,0.976396,0.587571,0.596924,2.618165,1.358864,33.640234,16.575786,24.923150,2.933323,...,3.725736,5059.046023,1114.272364,420.185822,15.627084,0.031723,0.040938,3369.645953,0.040933,0.031682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1754.000000,20.000000,1800.000000,0.000000,...,11.000000,0.000000,1001.000000,0.000000,20001.000000,38.819731,-77.113909,100.000000,-77.113135,38.820576
25%,39739.000000,1.000000,0.000000,1.000000,4.000000,2.000000,1918.000000,1985.000000,1954.000000,2.000000,...,11.000000,697.000000,1501.000000,616.000000,20007.000000,38.895425,-77.042892,2102.000000,-77.042894,38.895432
50%,79478.000000,2.000000,0.000000,1.000000,6.000000,3.000000,1937.000000,2004.000000,1963.000000,2.000000,...,13.000000,1649.000000,2265.000000,783.000000,20011.000000,38.915337,-77.019596,5201.000000,-77.019581,38.915229
75%,119217.000000,2.000000,1.000000,1.000000,7.000000,3.000000,1960.000000,2010.000000,1975.000000,2.000000,...,17.000000,3000.000000,2910.000000,1060.000000,20018.000000,38.936075,-76.988626,8302.000000,-76.988842,38.936077
max,158956.000000,14.000000,11.000000,6.000000,48.000000,24.000000,2019.000000,2019.000000,2018.000000,826.000000,...,117.000000,942632.000000,5621.000000,8553.000000,20392.000000,38.995540,-76.909758,11100.000000,-76.910511,38.993646